<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-MIAPP68" failures="2" tests="4" name="Test" time="17.35" errors="0" timestamp="2023-12-01T10:05:00 IST">
  <testcase classname="tests.LoginTest" name="testLogin" time="1.352">
    <failure type="java.lang.AssertionError" message="Sign Out is not Present">
      <![CDATA[java.lang.AssertionError: Sign Out is not Present
at tests.LoginTest.testLogin(LoginTest.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testLogin -->
  <testcase classname="tests.LoginTest" name="testLogin" time="3.606"/>
  <testcase classname="tests.LoginTest" name="testLogin" time="1.135">
    <failure type="java.lang.AssertionError" message="Sign Out is not Present">
      <![CDATA[java.lang.AssertionError: Sign Out is not Present
at tests.LoginTest.testLogin(LoginTest.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testLogin -->
  <testcase classname="tests.LoginTest" name="loginTestInvalid" time="0.018"/>
</testsuite> <!-- Test -->
